// Generated by scripts/ui_icons.py. React Native needs literal require() paths.
export const PIX = {
  heart: require('../../assets/icons/heart.png'),
  fire: require('../../assets/icons/fire.png'),
  pick: require('../../assets/icons/pick.png'),
  gem: require('../../assets/icons/gem.png'),
  wave: require('../../assets/icons/wave.png'),
  laugh: require('../../assets/icons/laugh.png'),
  note: require('../../assets/icons/note.png'),
  trophy: require('../../assets/icons/trophy.png'),
  gift: require('../../assets/icons/gift.png'),
  star: require('../../assets/icons/star.png'),
  chat: require('../../assets/icons/chat.png'),
  tunnel: require('../../assets/icons/tunnel.png'),
  pot: require('../../assets/icons/pot.png'),
  cart: require('../../assets/icons/cart.png'),
  lock: require('../../assets/icons/lock.png'),
  check: require('../../assets/icons/check.png'),
} as const;
export type PixName = keyof typeof PIX;
